# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "findyourway.local"

  config.vm.network "private_network", ip: "192.168.33.10"


#
# Répertoire partagés
# -> /var/www : pour avoir le docroot sur la machine hôte
# -> /etc/apache2 : pour avoir la config apache sur la machine hôte
# les répertoires sur la machine hôte doivent exister (./www, ./conf)
#

  config.vm.synced_folder "./www", "/var/www",
mount_options: ["dmode=775,fmode=664"]

#
#  sur une machine non-windows : on peut décommander
  config.vm.synced_folder "./conf", "/etc/apache2"

# provisioning :
# installer apache2 et autres choses si besoin

  config.vm.provision "shell", path: "./init_apache.sh"


end
